#!/usr/bin/env python3
"""Reproducible builder for the AI-PR failure taxonomy.

Layers:
  RAW (machine, re-fetchable): cache/prs/<owner>__<repo>__<num>.json
  LABELS (human, versioned):   data/labels.jsonl  -- ALSO the manifest:
        the dataset = exactly the PRs that have a label record (key "owner/repo#num").
  data/prs.jsonl is GENERATED by a deterministic merge of the two.

Commands:
  fetch    ensure every labelled PR has a cache file (fetch missing via gh), then build.  [network]
  rebuild  build from cache + labels only.  [offline, byte-identical -- the Day-2 oracle]
  hash     print sha256 of data/prs.jsonl.
"""
import argparse, hashlib, json, subprocess
from pathlib import Path

CACHE  = Path("cache/prs")
LABELS = Path("data/labels.jsonl")
OUT    = Path("data/prs.jsonl")
RAW_FIELDS = "number,title,state,author,createdAt,closedAt,mergedAt,url,labels,isDraft"

def cache_file(repo, number):
    return CACHE / f"{repo.replace('/', '__')}__{number}.json"

def load_labels():
    recs = []
    if LABELS.exists():
        for line in LABELS.read_text(encoding="utf-8").splitlines():
            if line.strip():
                recs.append(json.loads(line))
    return recs

def gh_fetch(repo, number):
    r = subprocess.run(["gh", "pr", "view", str(number), "--repo", repo,
                        "--json", RAW_FIELDS], capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit(f"gh failed for {repo}#{number}: {r.stderr.strip()}")
    return json.loads(r.stdout)

def outcome(raw):
    if raw.get("mergedAt"):
        return "merged"
    return "open" if raw.get("state", "").lower() == "open" else "closed"

def merged_row(repo, number, raw, lab):
    ev = lab.get("evidence", {}) or {}
    return {
        "repo": repo, "number": number, "url": raw["url"],
        "title": raw.get("title", ""),
        "author": (raw.get("author") or {}).get("login", ""),
        "created_at": raw.get("createdAt", ""),
        "outcome": outcome(raw),
        "state": raw.get("state", "").lower(),
        "merged_at": raw.get("mergedAt") or "",
        "closed_at": raw.get("closedAt") or "",
        "gh_labels": sorted(l["name"] for l in (raw.get("labels") or [])),
        "is_draft": bool(raw.get("isDraft", False)),
        "signals": sorted(lab.get("signals", [])),
        "signal_confidence": lab.get("signal_confidence", ""),
        "evidence": {"quote": ev.get("quote", ""), "link": ev.get("link", raw["url"])},
        "failure_class": lab.get("failure_class", "unclassified"),
        "failure_hypothesis": lab.get("failure_hypothesis", ""),
        "close_reason_quote": lab.get("close_reason_quote", ""),
        "repro_status": lab.get("repro_status", "pending"),
        "notes": lab.get("notes", ""),
    }

def build():
    rows = []
    for lab in load_labels():
        repo, num = lab["key"].rsplit("#", 1)
        number = int(num)
        cf = cache_file(repo, number)
        if not cf.exists():
            raise SystemExit(f"missing cache for {lab['key']} -- run `fetch` first")
        rows.append(merged_row(repo, number, json.loads(cf.read_text(encoding="utf-8")), lab))
    rows.sort(key=lambda r: (r["repo"], r["number"]))          # total, stable order
    lines = [json.dumps(r, sort_keys=True, ensure_ascii=False,
                        separators=(",", ":")) for r in rows]
    OUT.write_text("\n".join(lines) + ("\n" if lines else ""),
                   encoding="utf-8", newline="\n")
    return len(rows)

def fetch():
    CACHE.mkdir(parents=True, exist_ok=True)
    for lab in load_labels():
        repo, num = lab["key"].rsplit("#", 1)
        cf = cache_file(repo, int(num))
        if cf.exists():
            continue
        raw = gh_fetch(repo, int(num))
        cf.write_text(json.dumps(raw, sort_keys=True, ensure_ascii=False,
                                 separators=(",", ":")), encoding="utf-8", newline="\n")
        print(f"cached {lab['key']}")
    return build()

def main():
    cmd = argparse.ArgumentParser().add_subparsers(dest="c") or None
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["fetch", "rebuild", "hash"])
    c = ap.parse_args().cmd
    if c == "fetch":
        print(f"built {OUT} with {fetch()} rows")
    elif c == "rebuild":
        print(f"rebuilt {OUT} with {build()} rows")
    elif c == "hash":
        print(hashlib.sha256(OUT.read_bytes()).hexdigest())

if __name__ == "__main__":
    main()
